// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"iotfast/internal/app/system/dao/internal"
)

// internalSysGenTableDao is internal type for wrapping internal DAO implements.
type internalSysGenTableDao = *internal.SysGenTableDao

// sysGenTableDao is the data access object for table sys_gen_table.
// You can define custom methods on it to extend its functionality as you wish.
type sysGenTableDao struct {
	internalSysGenTableDao
}

var (
	// SysGenTable is globally public accessible object for table sys_gen_table operations.
	SysGenTable = sysGenTableDao{
		internal.NewSysGenTableDao(),
	}
)

// Fill with you ideas below.
