// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"iotfast/internal/app/system/dao/internal"
)

// internalSysAuthRuleDao is internal type for wrapping internal DAO implements.
type internalSysAuthRuleDao = *internal.SysAuthRuleDao

// sysAuthRuleDao is the data access object for table sys_auth_rule.
// You can define custom methods on it to extend its functionality as you wish.
type sysAuthRuleDao struct {
	internalSysAuthRuleDao
}

var (
	// SysAuthRule is globally public accessible object for table sys_auth_rule operations.
	SysAuthRule = sysAuthRuleDao{
		internal.NewSysAuthRuleDao(),
	}
)

// Fill with you ideas below.
