// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/xiaodingding/iotfast/internal/app/system/dao/internal"
)

// internalSysGenTableColumnDao is internal type for wrapping internal DAO implements.
type internalSysGenTableColumnDao = *internal.SysGenTableColumnDao

// sysGenTableColumnDao is the data access object for table sys_gen_table_column.
// You can define custom methods on it to extend its functionality as you wish.
type sysGenTableColumnDao struct {
	internalSysGenTableColumnDao
}

var (
	// SysGenTableColumn is globally public accessible object for table sys_gen_table_column operations.
	SysGenTableColumn = sysGenTableColumnDao{
		internal.NewSysGenTableColumnDao(),
	}
)

// Fill with you ideas below.
